export const HOME_PAGE = "/home"
export const GALLERY_PAGE = "/gallery"
export const CONTACT_PAGE = "/contact"
export const SPOT_PAGE = "/spot-the-station"
export const NOW_IN_SPACE_PAGE = "/now-in-space"
